import React from 'react';
import {
  NoteIcon,
  HomeIcon,
  CpuChipIcon,
  PinIcon,
  LockIcon,
  ChevronUpIcon,
  OntologyIcon,
  NetworkIcon,
  ChatIcon,
  SettingsIcon,
  PlusIcon,
  TrashIcon,
  SparklesIcon,
  KeyIcon,
  UserPlusIcon,
  UserGroupIcon,
  WorldIcon,
  EditIcon,
  SendIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ChevronDownIcon,
  PlusCircleIcon,
  CodeBracketsIcon,
  CubeIcon,
  CubeTransparentIcon,
  TagIcon,
  DocumentDuplicateIcon,
  ClipboardIcon,
  XCircleIcon,
  CheckCircleIcon,
  InformationCircleIcon,
  ExclamationTriangleIcon,
  XMarkIcon,
  SearchIcon,
  MapIcon,
  MapPinIcon,
  FolderIcon,
  MergeIcon,
  CheckIcon,
  XIcon,
  PencilIcon,
  ClockIcon,
  HelpIcon,
  SearchSparkleIcon,
  SidebarIcon,
  DownloadIcon,
} from '../common/icons';

type IconProps = React.SVGProps<SVGSVGElement>;

export const ICON_MAP: Record<string, React.FC<IconProps>> = {
  'note': NoteIcon,
  'home': HomeIcon,
  'cpu': CpuChipIcon,
  'pin': PinIcon,
  'lock': LockIcon,
  'chevron-up': ChevronUpIcon,
  'ontology': OntologyIcon,
  'network': NetworkIcon,
  'chat': ChatIcon,
  'settings': SettingsIcon,
  'plus': PlusIcon,
  'trash': TrashIcon,
  'sparkles': SparklesIcon,
  'key': KeyIcon,
  'user-plus': UserPlusIcon,
  'user-group': UserGroupIcon,
  'world': WorldIcon,
  'edit': EditIcon,
  'send': SendIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-right': ArrowRightIcon,
  'chevron-down': ChevronDownIcon,
  'plus-circle': PlusCircleIcon,
  'code-brackets': CodeBracketsIcon,
  'cube': CubeIcon,
  'cube-transparent': CubeTransparentIcon,
  'tag': TagIcon,
  'document-duplicate': DocumentDuplicateIcon,
  'clipboard': ClipboardIcon,
  'x-circle': XCircleIcon,
  'check-circle': CheckCircleIcon,
  'information-circle': InformationCircleIcon,
  'exclamation-triangle': ExclamationTriangleIcon,
  'x-mark': XMarkIcon,
  'search': SearchIcon,
  'map': MapIcon,
  'map-pin': MapPinIcon,
  'folder': FolderIcon,
  'merge': MergeIcon,
  'check': CheckIcon,
  'x': XIcon,
  'pencil': PencilIcon,
  'clock': ClockIcon,
  'help': HelpIcon,
  'search-sparkle': SearchSparkleIcon,
  'sidebar': SidebarIcon,
  'download': DownloadIcon,
};
