import React from 'react';
import {
    ArrowLeftIcon,
    ArrowRightIcon,
    ChatIcon,
    CheckCircleIcon,
    CheckIcon,
    ChevronDownIcon,
    ChevronUpIcon,
    ClipboardIcon,
    ClockIcon,
    CodeBracketsIcon,
    CpuChipIcon,
    CubeIcon,
    CubeTransparentIcon,
    DocumentDuplicateIcon,
    DownloadIcon,
    EditIcon,
    ExclamationTriangleIcon,
    FolderIcon,
    HelpIcon,
    HomeIcon,
    InformationCircleIcon,
    KeyIcon,
    LockIcon,
    MapIcon,
    MapPinIcon,
    MergeIcon,
    NetworkIcon,
    NoteIcon,
    OntologyIcon,
    PencilIcon,
    PinIcon,
    PlusCircleIcon,
    PlusIcon,
    SearchIcon,
    SearchSparkleIcon,
    SendIcon,
    SettingsIcon,
    SidebarIcon,
    SparklesIcon,
    TagIcon,
    TrashIcon,
    UserGroupIcon,
    UserPlusIcon,
    WorldIcon,
    XCircleIcon,
    XIcon,
    XMarkIcon,
} from '../common/icons';

type IconProps = React.SVGProps<SVGSVGElement>;

export const ICON_MAP: Record<string, React.FC<IconProps>> = {
    'note': NoteIcon,
    'home': HomeIcon,
    'cpu': CpuChipIcon,
    'pin': PinIcon,
    'lock': LockIcon,
    'chevron-up': ChevronUpIcon,
    'ontology': OntologyIcon,
    'network': NetworkIcon,
    'chat': ChatIcon,
    'settings': SettingsIcon,
    'plus': PlusIcon,
    'trash': TrashIcon,
    'sparkles': SparklesIcon,
    'key': KeyIcon,
    'user-plus': UserPlusIcon,
    'user-group': UserGroupIcon,
    'world': WorldIcon,
    'edit': EditIcon,
    'send': SendIcon,
    'arrow-left': ArrowLeftIcon,
    'arrow-right': ArrowRightIcon,
    'chevron-down': ChevronDownIcon,
    'plus-circle': PlusCircleIcon,
    'code-brackets': CodeBracketsIcon,
    'cube': CubeIcon,
    'cube-transparent': CubeTransparentIcon,
    'tag': TagIcon,
    'document-duplicate': DocumentDuplicateIcon,
    'clipboard': ClipboardIcon,
    'x-circle': XCircleIcon,
    'check-circle': CheckCircleIcon,
    'information-circle': InformationCircleIcon,
    'exclamation-triangle': ExclamationTriangleIcon,
    'x-mark': XMarkIcon,
    'search': SearchIcon,
    'map': MapIcon,
    'map-pin': MapPinIcon,
    'folder': FolderIcon,
    'merge': MergeIcon,
    'check': CheckIcon,
    'x': XIcon,
    'pencil': PencilIcon,
    'clock': ClockIcon,
    'help': HelpIcon,
    'search-sparkle': SearchSparkleIcon,
    'sidebar': SidebarIcon,
    'download': DownloadIcon,
};
