import * as readline from 'readline';
import chalk from 'chalk';
import { CliClient } from './client.js';
import { log, withSpinner } from './utils.js';

export async function runSetupWizard(cli: CliClient) {
    console.log('\n' + chalk.bold.blue('Welcome to Notention Setup Wizard! 🧙‍♂️') + '\n');

    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
    });

    const ask = (query: string): Promise<string> => {
        return new Promise(resolve => rl.question(chalk.green('? ') + query + ' ', resolve));
    };

    try {
        const name = await ask('What should I call you? (User)');
        const privacy = await ask('Privacy Mode (local-only / shared) [local-only]:');
        const aiProvider = await ask('AI Provider (openai / ollama / anthropic) [openai]:');
        const aiModel = await ask('AI Model (e.g. gpt-4o) [gpt-4o]:');

        const config = {
            name: name || 'User',
            privacy: privacy || 'local-only',
            provider: aiProvider || 'openai',
            model: aiModel || 'gpt-4o'
        };

        console.log('\n' + chalk.yellow('Generating configuration...') + '\n');

        const properties = [
            `[user:name:is:${config.name}]`,
            `[privacy:level:is:${config.privacy}]`,
            `[ai:provider:is:${config.provider}]`,
            `[ai:model:is:${config.model}]`,
            `[ai:enabled:is:true]`,
            `[capability:files:is:true]`
        ];

        const content = `# System Configuration
@config:active
@setup

Configuration generated by CLI Setup Wizard.

${properties.join('\n')}
        `;

        await withSpinner('Saving configuration...', async () => {
            await cli.callTool('create_note', {
                title: 'System Configuration',
                content: content,
                tags: ['@config:active', 'config', 'setup'],
                properties: [
                    { key: 'user:name', operator: 'is', values: [config.name] },
                    { key: 'privacy:level', operator: 'is', values: [config.privacy] },
                    { key: 'ai:provider', operator: 'is', values: [config.provider] },
                    { key: 'ai:model', operator: 'is', values: [config.model] },
                    { key: 'ai:enabled', operator: 'is', values: ['true'] },
                    { key: 'capability:files', operator: 'is', values: ['true'] }
                ]
            });
        });

        // Cleanup onboarding note
        await withSpinner('Cleaning up...', async () => {
            const result = await cli.callTool('read_notes', { tags: ['@onboarding:setup'] });
            // MCP Tool execution result structure
            const content = (result as any).content;
            if (content && content[0] && content[0].text) {
                const notes = JSON.parse(content[0].text);
                if (Array.isArray(notes)) {
                    for (const note of notes) {
                        await cli.callTool('delete_note', { id: note.id });
                    }
                }
            }
        });

        log.success('Setup complete! You are ready to go.');

    } catch (e: any) {
        log.error('Setup failed', e);
    } finally {
        rl.close();
    }
}
